name: Go Lint

on:
  push:
    branches:
      - "**"  # Runs on all branches EXCEPT when part of a PR
  pull_request:  # Runs only on PR updates
    types: [opened, synchronize, reopened]  # Runs only on PR updates

permissions:
  contents: read

jobs:
  lint:
    name: Run Go Linter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.0'

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install make
        run: sudo apt-get update && sudo apt-get install -y make

      - name: Run Linter via Makefile
        run: make lint
